kfrederick_dev: 116_Jorgensen_YKDE review
ISCN/SOCDRaHR2 pull request #73
Opened 2021-04-08 16:48 UTC by kristenfrederick

116_Jorgensen_YKDE is ready for review. #57

2021-04-08 18:59 UTC, ktoddbrown requested changes

2021-04-08 18:59 UTC, ktoddbrown commented on data_reports/116_Jorgensen_YKDE.Rmd
> +The Jorgensen YKDE data set in ISCN3 contains `r nrow(dataset_layer)` layer-level rows and `r nrow(dataset_profile)` profile-level information rows after cleaning for ISCN3.5.
Need to actually put the number here since the dataset_layer and dataset_profile are not ingested yet.

2021-04-08 18:59 UTC, ktoddbrown commented on data_reports/116_Jorgensen_YKDE.Rmd
> +Columns were removed from ISCN3 because ISCN3 filled in the soil carbon stocks where bulk density and organic carbon was provided.
This contradicts with the line above.

2021-04-08 18:59 UTC, ktoddbrown commented on index.Rmd
> +citation_raw <- read_delim('~/ISCN/ISCN3_citation.csv', delim = ';', col_types = strrep('c', times = 12)) %>%
Use file.path instead here.

2021-04-08 18:59 UTC, ktoddbrown commented on index.Rmd
> +=======
Remove this like, likely from a merge

2021-04-14 18:17 UTC, kristenfrederick commented
The pull request is ready for a second review

2021-04-19 13:56 UTC, ktoddbrown approved these changes
Looks good!

2021-04-19 13:56 UTC, merged